<?php
declare(strict_types=1);

/*
 * (c) 2020 Georg Großberger <contact@grossberger-ge.org>
 *
 * This file is free software; you can redistribute it and/or
 * modify it under the terms of the Apache License 2.0
 *
 * For the full copyright and license information see
 * <https://www.apache.org/licenses/LICENSE-2.0>
 */

return [
    'Andorra la Vella',
    'Abu Dhabi',
    'Kabul',
    'St John\'s',
    'The Valley',
    'Tirana',
    'Yerevan',
    'Willemstad',
    'Luanda',
    'Buenos Aires',
    'Pago Pago',
    'Vienna',
    'Canberra',
    'Oranjestad',
    'Baku',
    'Sarajevo',
    'Bridgetown',
    'Dhaka',
    'Brussels',
    'Ouagadougou',
    'Sofia',
    'Manama',
    'Bujumbura',
    'Porto Novo',
    'Hamilton',
    'Bandar Seri Begawan',
    'Sucre',
    'Brasilia',
    'Nassau',
    'Thimphu',
    'Gaborone',
    'Minsk',
    'Belmopan',
    'Ottawa',
    'Bantam',
    'Kinshasa',
    'Bangui',
    'Brazzaville',
    'Berne',
    'Yamoussoukro',
    'Avarua',
    'Santiago',
    'Yaoundé',
    'Beijing',
    'Bogotá',
    'San José',
    'Havana',
    'Praia',
    'Flying Fish Cove',
    'Nicosia',
    'Prague',
    'Berlin',
    'Djibouti',
    'Copenhagen',
    'Roseau',
    'Santo Domingo',
    'Algiers',
    'Quito',
    'Tallinn',
    'Cairo',
    'El Aaiún',
    'Asmara',
    'Madrid',
    'Addis Ababa',
    'Helsinki',
    'Suva',
    'Stanley',
    'Palikir',
    'Thorshavn',
    'Paris',
    'Libreville',
    'London',
    'St George\'s',
    'Tbilisi',
    'Cayenne',
    'Accra',
    'Gibraltar',
    'Nuuk',
    'Banjul',
    'Conakry',
    'Basse Terre',
    'Malabo',
    'Athens',
    'Guatemala City',
    'Hagåtña',
    'Bissau',
    'Georgetown',
    'Tegucigalpa',
    'Zagreb',
    'Port-au-Prince',
    'Budapest',
    'Jakarta',
    'Dublin',
    'Tel Aviv',
    'New Delhi',
    'Baghdad',
    'Tehran',
    'Reykjavík',
    'Rome',
    'Kingston',
    'Amman',
    'Tokyo',
    'Nairobi',
    'Bishkek',
    'Phnom Penh',
    'Bairiki',
    'Moroni',
    'Basseterre',
    'Pyongyang',
    'Seoul',
    'Kuwait City',
    'George Town',
    'Astana',
    'Vientiane',
    'Beirut',
    'Castries',
    'Vaduz',
    'Colombo',
    'Monrovia',
    'Maseru',
    'Vilnius',
    'Luxembourg',
    'Riga',
    'Tripoli',
    'Rabat',
    'Monaco',
    'Chisinau',
    'Antananarivo',
    'Dalap-Uliga-Darrit (DUD)',
    'Skopje',
    'Bamako',
    'Yangon',
    'Ulan Bator',
    'Macau',
    'Garapan',
    'Fort-de-France',
    'Nouakchott',
    'Plymouth',
    'Valletta',
    'Port Louis',
    'Malé',
    'Lilongwe',
    'Mexico City',
    'Kuala Lumpur',
    'Maputo',
    'Windhoek',
    'Nouméa',
    'Niamey',
    'Kingston',
    'Abuja',
    'Managua',
    'Amsterdam',
    'Oslo',
    'Kathmandu',
    'Yaren',
    'Alofi',
    'Wellington',
    'Muscat',
    'Panama City',
    'Lima',
    'Papeete',
    'Port Moresby',
    'Manila',
    'Islamabad',
    'Warsaw',
    'Saint-Pierre',
    'Adamstown',
    'San Juan',
    'Lisbon',
    'Koror',
    'Asunción',
    'Doha',
    'Saint-Denis',
    'Bucharest',
    'Moscow',
    'Kigali',
    'Riyadh',
    'Honiara',
    'Victoria',
    'Khartoum',
    'Stockholm',
    'Singapore',
    'Jamestown',
    'Ljubljana',
    'Longyearbyen',
    'Bratislava',
    'Freetown',
    'San Marino',
    'Dakar',
    'Mogadishu',
    'Paramaribo',
    'São Tomé',
    'San Salvador',
    'Damascus',
    'Mbabane',
    'Cockburn Town',
];
