<?php
declare(strict_types=1);

/*
 * (c) 2020 Georg Großberger <contact@grossberger-ge.org>
 *
 * This file is free software; you can redistribute it and/or
 * modify it under the terms of the Apache License 2.0
 *
 * For the full copyright and license information see
 * <https://www.apache.org/licenses/LICENSE-2.0>
 */

return [
    'Walmart',
    'Exxon Mobil',
    'Apple',
    'Berkshire Hathaway',
    'McKesson',
    'UnitedHealth Group',
    'CVS Health',
    'General Motors',
    'Ford Motor',
    'AT&T',
    'General Electric',
    'AmerisourceBergen',
    'Verizon',
    'Chevron',
    'Costco',
    'Fannie Mae',
    'Kroger',
    'Amazon.com',
    'Walgreens Boots Alliance',
    'HP',
    'Cardinal Health',
    'Express Scripts Holding',
    'J.P. Morgan Chase',
    'Boeing',
    'Microsoft',
    'Bank of America Corp.',
    'Wells Fargo',
    'Home Depot',
    'Citigroup',
    'Phillips 66',
    'IBM',
    'Valero Energy',
    'Anthem',
    'Procter & Gamble',
    'State Farm Insurance Cos.',
    'Alphabet',
    'Comcast',
    'Target',
    'Johnson & Johnson',
    'MetLife',
    'Archer Daniels Midland',
    'Marathon Petroleum',
    'Freddie Mac',
    'PepsiCo',
    'United Technologies',
    'Aetna',
    'Lowe’s',
    'UPS',
    'AIG',
    'Prudential Financial',
    'Intel',
    'Humana',
    'Disney',
    'Cisco Systems',
    'Pfizer',
    'Dow Chemical',
    'Sysco',
    'FedEx',
    'Caterpillar',
    'Lockheed Martin',
    'New York Life Insurance',
    'Coca-Cola',
    'HCA Holdings',
    'Ingram Micro',
    'Energy Transfer Equity',
    'Tyson Foods',
    'American Airlines Group',
    'Delta Air Lines',
    'Nationwide',
    'Johnson Controls',
    'Best Buy',
    'Merck',
    'Liberty Mutual Insurance Group',
    'Goldman Sachs Group',
    'Honeywell International',
    'Massachusetts Mutual Life Insurance',
    'Oracle',
    'Morgan Stanley',
    'Cigna',
    'United Continental Holdings',
    'Allstate',
    'TIAA',
    'INTL FCStone',
    'CHS',
    'American Express',
    'Gilead Sciences',
    'Publix Super Markets',
    'General Dynamics',
    'TJX',
    'ConocoPhillips',
    'Nike',
    'World Fuel Services',
    '3M',
    'Mondelez International',
    'Exelon',
    'Twenty-First Century Fox',
    'Deere',
    'Tesoro',
    'Time Warner',
    'Northwestern Mutual',
    'DuPont',
    'Avnet',
    'Macy’s',
    'Enterprise Products Partners',
    'Travelers Cos.',
    'Philip Morris International',
    'Rite Aid',
    'Tech Data',
    'McDonald’s',
    'Qualcomm',
    'Sears Holdings',
    'Capital One Financial',
    'EMC',
    'USAA',
    'Duke Energy',
    'Time Warner Cable',
    'Halliburton',
    'Northrop Grumman',
    'Arrow Electronics',
    'Raytheon',
    'Plains GP Holdings',
    'US Foods Holding',
    'AbbVie',
    'Centene',
    'Community Health Systems',
    'Alcoa',
    'International Paper',
    'Emerson Electric',
    'Union Pacific',
    'Amgen',
    'U.S. Bancorp',
    'Staples',
    'Danaher',
    'Whirlpool',
    'Aflac',
    'AutoNation',
    'Progressive',
    'Abbott Laboratories',
    'Dollar General',
    'Tenet Healthcare',
    'Eli Lilly',
    'Southwest Airlines',
    'Penske Automotive Group',
    'ManpowerGroup',
    'Kohl’s',
    'Starbucks',
    'Paccar',
    'Cummins',
    'Altria Group',
    'Xerox',
    'Kimberly-Clark',
    'Hartford Financial Services Group',
    'Kraft Heinz',
    'Lear',
    'Fluor',
    'AECOM',
    'Facebook',
    'Jabil Circuit',
    'CenturyLink',
    'Supervalu',
    'General Mills',
    'Southern',
    'NextEra Energy',
    'Thermo Fisher Scientific',
    'American Electric Power',
    'PG&E Corp.',
    'NGL Energy Partners',
    'Bristol-Myers Squibb',
    'Goodyear Tire & Rubber',
    'Nucor',
    'PNC Financial Services Group',
    'Health Net',
    'Micron Technology',
    'Colgate-Palmolive',
    'Freeport-McMoRan',
    'ConAgra Foods',
    'Gap',
    'Baker Hughes',
    'Bank of New York Mellon Corp.',
    'Dollar Tree',
    'Whole Foods Market',
    'PPG Industries',
    'Genuine Parts',
    'Icahn Enterprises',
    'Performance Food Group',
    'Omnicom Group',
    'DISH Network',
    'FirstEnergy',
    'Monsanto',
    'AES',
    'CarMax',
    'National Oilwell Varco',
    'NRG Energy',
    'Western Digital',
    'Marriott International',
    'Office Depot',
    'Nordstrom',
    'Kinder Morgan',
    'Aramark',
    'DaVita HealthCare Partners',
    'Molina Healthcare',
    'WellCare Health Plans',
    'CBS',
    'Visa',
    'Lincoln National',
    'Ecolab',
    'Kellogg',
    'C.H. Robinson Worldwide',
    'Textron',
    'Loews',
    'Illinois Tool Works',
    'Synnex',
    'Viacom',
    'HollyFrontier',
    'Land O’Lakes',
    'Devon Energy',
    'PBF Energy',
    'Yum Brands',
    'Texas Instruments',
    'CDW',
    'Waste Management',
    'Marsh & McLennan',
    'Chesapeake Energy',
    'Parker-Hannifin',
    'Occidental Petroleum',
    'Guardian Life Ins. Co. of America',
    'Farmers Insurance Exchange',
    'J.C. Penney',
    'Consolidated Edison',
    'Cognizant Technology Solutions',
    'VF',
    'Ameriprise Financial',
    'Computer Sciences',
    'L Brands',
    'Jacobs Engineering Group',
    'Principal Financial',
    'Ross Stores',
    'Bed Bath & Beyond',
    'CSX',
    'Las Vegas Sands',
    'Leucadia National',
    'Dominion Resources',
    'United States Steel',
    'L-3 Communications',
    'Edison International',
    'Entergy',
    'ADP',
    'First Data',
    'BlackRock',
    'WestRock',
    'Voya Financial',
    'Sherwin-Williams',
    'Hilton Worldwide Holdings',
    'R.R. Donnelley & Sons',
    'Stanley Black & Decker',
    'Xcel Energy',
    'Murphy USA',
    'CBRE Group',
    'D.R. Horton',
    'Estee Lauder',
    'Praxair',
    'Biogen',
    'State Street Corp.',
    'Unum Group',
    'Reynolds American',
    'Group 1 Automotive',
    'Henry Schein',
    'Hertz Global Holdings',
    'Norfolk Southern',
    'Reinsurance Group of America',
    'Public Service Enterprise Group',
    'BB&T Corp.',
    'DTE Energy',
    'Assurant',
    'Global Partners',
    'Huntsman',
    'Becton Dickinson',
    'Sempra Energy',
    'AutoZone',
    'Navistar International',
    'Precision Castparts',
    'Discover Financial Services',
    'Liberty Interactive',
    'W.W. Grainger',
    'Baxter International',
    'Stryker',
    'Air Products & Chemicals',
    'Western Refining',
    'Universal Health Services',
    'Owens & Minor',
    'Charter Communications',
    'Advance Auto Parts',
    'MasterCard',
    'Applied Materials',
    'Eastman Chemical',
    'Sonic Automotive',
    'Ally Financial',
    'CST Brands',
    'eBay',
    'Lennar',
    'GameStop',
    'Reliance Steel & Aluminum',
    'Hormel Foods',
    'Celgene',
    'Genworth Financial',
    'PayPal Holdings',
    'Priceline Group',
    'MGM Resorts International',
    'Autoliv',
    'Fidelity National Financial',
    'Republic Services',
    'Corning',
    'Peter Kiewit Sons’',
    'Univar',
    'Mosaic',
    'Core-Mark Holding',
    'Thrivent Financial for Lutherans',
    'Cameron International',
    'HD Supply Holdings',
    'Crown Holdings',
    'EOG Resources',
    'Veritiv',
    'Anadarko Petroleum',
    'Laboratory Corp. of America',
    'Pacific Life',
    'News Corp.',
    'Jarden',
    'SunTrust Banks',
    'Avis Budget Group',
    'Broadcom',
    'American Family Insurance Group',
    'Level 3 Communications',
    'Tenneco',
    'United Natural Foods',
    'Dean Foods',
    'Campbell Soup',
    'Mohawk Industries',
    'BorgWarner',
    'PVH',
    'Ball',
    'OReilly Automotive',
    'Eversource Energy',
    'Franklin Resources',
    'Masco',
    'Lithia Motors',
    'KKR',
    'Oneok',
    'Newmont Mining',
    'PPL',
    'SpartanNash',
    'Quanta Services',
    'XPO Logistics',
    'Ralph Lauren',
    'Interpublic Group',
    'Steel Dynamics',
    'WESCO International',
    'Quest Diagnostics',
    'Boston Scientific',
    'AGCO',
    'Foot Locker',
    'Hershey',
    'CenterPoint Energy',
    'Williams',
    'Dick’s Sporting Goods',
    'Live Nation Entertainment',
    'Mutual of Omaha Insurance',
    'W.R. Berkley',
    'LKQ',
    'Avon Products',
    'Darden Restaurants',
    'Kindred Healthcare',
    'Weyerhaeuser',
    'Casey’s General Stores',
    'Sealed Air',
    'Fifth Third Bancorp',
    'Dover',
    'Huntington Ingalls Industries',
    'Netflix',
    'Dillards',
    'EMCOR Group',
    'Jones Financial',
    'AK Steel Holding',
    'UGI',
    'Expedia',
    'salesforce.com',
    'Targa Resources',
    'Apache',
    'Spirit AeroSystems Holdings',
    'Expeditors International of Washington',
    'Anixter International',
    'Fidelity National Information Services',
    'Asbury Automotive Group',
    'Hess',
    'Ryder System',
    'Terex',
    'Coca-Cola European Partners',
    'Auto-Owners Insurance',
    'Cablevision Systems',
    'Symantec',
    'Charles Schwab',
    'Calpine',
    'CMS Energy',
    'Alliance Data Systems',
    'JetBlue Airways',
    'Discovery Communications',
    'Trinity Industries',
    'Sanmina',
    'NCR',
    'FMC Technologies',
    'Erie Insurance Group',
    'Rockwell Automation',
    'Dr Pepper Snapple Group',
    'iHeartMedia',
    'Tractor Supply',
    'J.B. Hunt Transport Services',
    'Commercial Metals',
    'Owens-Illinois',
    'Harman International Industries',
    'Baxalta',
    'American Financial Group',
    'NetApp',
    'Graybar Electric',
    'Oshkosh',
    'Ameren',
    'A-Mark Precious Metals',
    'Barnes & Noble',
    'Dana Holding',
    'Constellation Brands',
    'LifePoint Health',
    'Zimmer Biomet Holdings',
    'Harley-Davidson',
    'PulteGroup',
    'Newell Brands',
    'Avery Dennison',
    'Jones Lang LaSalle',
    'WEC Energy Group',
    'Marathon Oil',
    'TravelCenters of America',
    'United Rentals',
    'HRG Group',
    'Old Republic International',
    'Windstream Holdings',
    'Starwood Hotels & Resorts',
    'Delek US Holdings',
    'Packaging Corp. of America',
    'Quintiles Transnational Holdings',
    'Hanesbrands',
    'Realogy Holdings',
    'Mattel',
    'Motorola Solutions',
    'J.M. Smucker',
    'Regions Financial',
    'Celanese',
    'Clorox',
    'Ingredion',
    'Genesis Healthcare',
    'Peabody Energy',
    'Alaska Air Group',
    'Seaboard',
    'Frontier Communications',
    'Amphenol',
    'Lansing Trade Group',
    'SanDisk',
    'St. Jude Medical',
    'Wyndham Worldwide',
    'Kelly Services',
    'Western Union',
    'Envision Healthcare Holdings',
    'Visteon',
    'Arthur J. Gallagher',
    'Host Hotels & Resorts',
    'Ashland',
    'Insight Enterprises',
    'Energy Future Holdings',
    'Markel',
    'Essendant',
    'CH2M Hill',
    'Western & Southern Financial Group',
    'Owens Corning',
    'S&P Global',
    'Raymond James Financial',
    'NiSource',
    'Airgas',
    'ABM Industries',
    'Citizens Financial Group',
    'Booz Allen Hamilton Holding',
    'Simon Property Group',
    'Domtar',
    'Rockwell Collins',
    'Lam Research',
    'Fiserv',
    'Spectra Energy',
    'Navient',
    'Big Lots',
    'Telephone & Data Systems',
    'First American Financial',
    'NVR',
    'Cincinnati Financial',
    'Burlington Stores',
];
